name: Tests
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  typescript:
    name: Bun Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout submodule
        uses: actions/checkout@v4
        with:
          repository: N1ckPro/aoc-inputs
          path: inputs
          ref: main
          ssh-key: ${{ secrets.INPUTS_ACCESS_KEY }}

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run Lint
        run: bun lint

      - name: Run Tests
        run: bun test
