name: Tests
on: [push, pull_request]
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true
jobs:
    typescript:
        name: Node.js Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Node.js
              uses: actions/setup-node@v4
              env:
                  SKIP_YARN_COREPACK_CHECK: 1
              with:
                  cache: yarn
                  cache-dependency-path: yarn.lock
                  node-version: 18.18.2

            - name: Install dependencies
              uses: yarn --immutable

            - name: Run Lint
              run: yarn lint

            - name: Run Tests
              run: yarn test
